#!/bin/sh
# wait-for.sh

set -e

host="$1"
shift

# --引数を処理してスキップする
if [ "$1" = "--" ]; then
  shift
fi

cmd="$@"

until mysql -h "$host" -u root -ppassword -e 'SELECT 1'; do
  >&2 echo "MySQL is unavailable - sleeping"
  sleep 1
done

>&2 echo "MySQL is up - executing command"
exec $cmd 