# frozen_string_literal: true

# Rswag::Api initializer
# Configuration for serving OpenAPI/Swagger documentation
Rswag::Api.configure do |c|
  # Specify a root folder where Swagger JSON files are generated
  # NOTE: If you're using the rswag-specs to generate Swagger, those files
  # are generated by default in the swagger_root folder
  c.openapi_root = Rails.root.join('swagger').to_s

  # Inject a lambda function to alter the returned Swagger prior to serialization
  # The function will have access to the rack env for the current request
  # For example, you could leverage this to dynamically assign the "host" property
  c.swagger_filter = lambda { |swagger, env| 
    swagger['host'] = env['HTTP_HOST']
    
    # Add security definitions
    swagger['securityDefinitions'] = {
      'Bearer' => {
        'type' => 'apiKey',
        'name' => 'Authorization',
        'in' => 'header',
        'description' => 'JWT authentication. Example: "Bearer {token}"'
      },
      'ApiKey' => {
        'type' => 'apiKey',
        'name' => 'X-API-Key',
        'in' => 'header',
        'description' => 'API key authentication'
      }
    }
    
    # Add global metadata
    swagger['x-api-version'] = 'v1'
    swagger['x-generated-at'] = Time.current.iso8601
  }
end